services:
  reverse-proxy:
    image: traefik:v2.6
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./traefik.yml:/traefik.yml:ro"
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    ports:
      - "5432:5432"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - db:/var/lib/postgresql/data
  todo:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todo.entrypoints=web"
      - "traefik.http.routers.todo.rule=Host(`todo.localhost`)"
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - db
volumes:
    db:
      driver: local
