services:
  postgres:
    image: postgres:14.2-alpine
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    ports:
      - 5432:5432
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 20

  backend:
    build:
      context: ./backend
    container_name: backend
    command: npm start
    ports:
      - 3001:3001
    depends_on:
      postgres:
        condition: service_healthy

  client:
    build:
      context: ./client
    volumes:
      - /app
      - /app/node_modules
    ports:
      - 3000:3000

volumes:
  postgres:
