services:
  reverse-proxy:
    image: traefik:v2.6
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./traefik.yml:/traefik.yml:ro"
  todo:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todo.entrypoints=web"
      - "traefik.http.routers.todo.rule=Host(`todo.localhost`)"
