## STATIC CONFIGURATION
log:
  level: INFO

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
  postgres:
    address: ":5432"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
